main: se.spreadthebread.mctestrpg.App
name: MCTestRPG
version: 0.1
author: Wapic
api-version: 1.13
commands:
  troll:
    description: Troll players
    usage: /troll (Playername)
    permission: mctestrpg.troll
    permission-message: You don't have permission to troll!
  skills:
    description: check your skills
    usage: /skills
    permission: mctestrpg.skills
    permission-message: You don't have permission to check your skills!
  bank:
    description: opens your bank
    usage: /bank
    permission: mctestrpg.bank
    permission-message: You don't have permission to open your bank!